command = """
CREATE TABLE IF NOT EXISTS pemasukan(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    username TEXT,
    nama TEXT,
    nama_keluarga TEXT,
    bulan TEXT,
    nominal INTEGER,
    huria INTEGER,
    pembangunan INTEGER,
    diakonia INTEGER,
    pendeta INTEGER,
    sintua INTEGER,
    perhalado INTEGER,
    ama INTEGER,
    ina INTEGER,
    nhkbp INTEGER,
    remaja INTEGER,
    sekolah_minggu INTEGER,
    pemusik INTEGER,
    multimedia INTEGER,
    song_leader INTEGER,
    pemasukan_pagi INTEGER,
    pemasukan_sore INTEGER,
    pemasukan_sekolah INTEGER,
    pemasukan_kasual INTEGER,
    pemasukan_partangiangan INTEGER,
    pemasukan_kategori INTEGER,
    transitori INTEGER,
    pemasukan_lainnya INTEGER,
    total INTEGER,
    tanggal TEXT,
    keterangan TEXT,
    status TEXT,
    bukti TEXT
"""
cursor.execute(command)

comman = """
    CREATE TABLE IF NOT EXISTS pengeluaran(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT,
    nama TEXT,
    nama_keluarga TEXT,
    bulan TEXT,
    nominal INTEGER,
    huria INTEGER,
    pembangunan INTEGER,
    diakonia INTEGER,
    pendeta INTEGER,
    sintua INTEGER,
    perhalado INTEGER,
    ama INTEGER,
    ina INTEGER,
    nhkbp INTEGER,
    remaja INTEGER,
    sekolah_minggu INTEGER,
    pemusik INTEGER,
    multimedia INTEGER,
    song_leader INTEGER,
    pemasukan_pagi INTEGER,
    pemasukan_sore INTEGER,
    pemasukan_sekolah INTEGER,
    pemasukan_kasual INTEGER,
    pemasukan_partangiangan INTEGER,
    pemasukan_kategori INTEGER,
    transitori INTEGER,
    pemasukan_lainnya INTEGER,
"""